### PR TITLE
Ember 1.13 Support

### PR DESCRIPTION
**Pull request by Kilowhisky**
Extends https://github.com/kurko/ember-localstorage-adapter/pull/124

To add support for ember 1.13+

This has two failing tests that i think should just be removed.

### CODE REVIEW

**Comment by mylen** [comment]
I, I'm interested by you pull request. Could you let me know how to use it in my project please? I make heavy use of the local storage adapter in my application, but I am thinking of switching to something more reliable as I have tons of problems every time I update my project.

**Comment by Kilowhisky** [comment]
You can just change the local storage adapter reference line in the package.json file to use my branch until this gets pulled or another one comes along and gets merged into the main.

```
"ember-localstorage-adapter": "git://github.com/Kilowhisky/ember-localstorage-adapter.git#ember-1.13.+",
```

**Comment by mylen** [comment]
Tank you for your help!
Le sam. 22 août 2015 à 01:44, Kilowhisky <notifications@github.com> a
écrit :

**Comment by mylen** [comment]
I get an error when trying to install:

$ npm install --save-dev "
https://github.com/Kilowhisky/ember-localstorage-adapter.git#ember-1.13.+"

npm ERR! Command failed: git -c core.longpaths=true clone
--template=C:\Users\alex\AppData\Roaming\npm-cache\_git-remotes\_templates
--mirror git@github.com:Kilowhisky/ember-localstorage-adapter.git
C:\Users\alex\AppData\Roaming\npm-cache\_git-remotes\git-github-com-Kilowhisky-ember-localstorage-adapter-git-dc5accbf
npm ERR! Clonage dans le dépôt nu
'C:\Users\alex\AppData\Roaming\npm-cache\_git-remotes\git-github-com-Kilowhisky-ember-localstorage-adapter-git-dc5accbf'
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.

Do you have any idea where it's from?

Thanks for your help if you mind to share some time on this

**Comment by kurko** [comment]
@Kilowhisky merging. Any chance you can PR a fix for those deprecations? :smile:

**Pull request merged**
