### PR TITLE
Support Ember Data beta.17

### LINKED ISSUE #116: Support Ember Data beta.17
Hi, after upgrading Ember Data to beta 17, this adapter is broken. The console gives me this error: `TypeError: snapshot.hasMany(...) is undefined`. Seems like they changed the syntax for `hasMany()` function call. 

Once I replaced the line `json[payloadKey] = snapshot.hasMany(key).mapBy('id');` with `json[payloadKey] = snapshot.hasMany(key, { ids: true });` things are functional again.

Could we update adapter to support beta 17? Thanks!

### PR DESCRIPTION
**Pull request by ujamer**
fixes #116.

### CODE REVIEW

**Comment by kurko** [comment]
Hey you have any idea why it's failing? I have other repos failing as well...

**Comment by ujamer** [comment]
Er, I think it's because bower installs Ember Data beta.18 and Ember 1.12.0, both of which introduces deprecations that affects the adapter. I'll take a closer look tomorrow.

**Comment by ujamer** [comment]
Okay, got tests to pass again.
There's a lot of deprecation warnings though. Will look at those next.

**Comment by ujamer** [comment]
Removed all deprecation warnings except for the one about `Ember.reduceComputed`. Any idea one what it's about?

**Comment by kurko** [comment]
Nope. Never saw it before.

**Comment by srsgores** [comment]
Can we bump version, and ``npm publish`` please?

**Comment by kurko** [comment]
Published!

**Pull request merged**
