### PR TITLE
bring up to date with ember-data 0.16

### LINKED ISSUE #106: DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead.
I am getting this warning with the ember-data 1.0.0-beta.16.1.
This is related with the recent Snapshot API changes on 1.0.0-beta.16.1 
http://emberjs.com/blog/2015/03/23/ember-data-1-0-beta-16-released.html#toc_the-store-now-passes-snapshots-instead-of-records-to-adapter-methods
Thanks.

### PR DESCRIPTION
**Pull request by csantero**
This fixes #106 and eliminates the deprecation warnings from upgrading to ember-data 0.16.1.

### CODE REVIEW

**Comment by vsymguysung** [comment]
This works fine. @kurko  What is your schedule to accept this pull request? or any other thoughts on this?

**Comment by kurko** [comment]
Thanks @csantero :smile: 

@vsymguysung thanks for the comments. It's important to have someone testing it so we feel more confident when merging :smile:

**Comment by csantero** [comment]
@kurko Glad to help. Any chance you could cut a new release on npm?

**Comment by mylen** [comment]
:+1: I would apreciate that too :)

**Comment by kurko** [comment]
Will do it tonight.

**Comment by joesiewert** [comment]
:clap: Cool, I think this will clear up errors I'm getting as well. Thanks for the fix @csantero

**Pull request merged**
